#!/usr/bin/env python3
"""Freeze the Orsy mapping to a data file the firmware can embed.

The generators rank chords by corpus frequency, so their output moves if the
corpus or the tie-breaking changes.  An implementation needs a fixed mapping,
so this writes one out with explicit key bits.  Regenerating it is a
deliberate act that should show up as a diff.
"""

import collections
import json
import sys

from m4t import corpus, layout as L, theory, writer

# Per-hand key bits, as the Dosh table already numbers them.  mesa3 has no
# upper pinky, so 0x010 is absent.
KEY_BITS = {
    "a": 0x001, "o": 0x002, "t": 0x004, "e": 0x008,
    "s": 0x020, "n": 0x040, "i": 0x080, "Sp": 0x100, "Bk": 0x200,
}
OUTER_MASK = 0x067          # a o s t n
INNER_MASK = 0x388          # e i Sp Bk


def bits(chord):
    total, i = 0, 0
    while i < len(chord):
        for k in ("Sp", "Bk"):
            if chord.startswith(k, i):
                total |= KEY_BITS[k]
                i += 2
                break
        else:
            total |= KEY_BITS[chord[i]]
            i += 1
    return total


def keys(chord):
    out, i = [], 0
    while i < len(chord):
        for k in ("Sp", "Bk"):
            if chord.startswith(k, i):
                out.append(k)
                i += 2
                break
        else:
            out.append(chord[i])
            i += 1
    return out


def main():
    import first_pass as F
    import propose_mesa3 as P
    import structured_map as S

    cons, _ = P.frequencies()
    cmap, _, _ = S.build(cons)
    d = corpus.load()
    chunks = writer.index(d)
    words = []
    for line in open("../words/count_1w.txt", encoding="utf-8", errors="replace"):
        p = line.split()
        if len(p) == 2 and p[0].isalpha():
            words.append((p[0], int(p[1])))
    words = words[:20000]
    f2 = collections.Counter()
    for w, fr in words:
        for st in writer.write(w, chunks):
            s2 = L.split(st)[1]
            if s2:
                f2[s2] += fr
    s2map = F.series2_map(f2)

    out = {
        "name": "orsy",
        "note": "Generated by midi4text-analysis/freeze.py. Do not edit by hand.",
        "key_bits": KEY_BITS,
        "outer_mask": OUTER_MASK,
        "inner_mask": INNER_MASK,
        "outer": [],
        "inner_right": [],
        "inner_left": [],
        "commands": [],
    }

    for shape, _ in cons.most_common():
        if shape not in cmap:
            continue
        out["outer"].append({
            "michela": shape,
            "onset": theory.ONSET.get(shape),
            "coda": theory.CODA.get(L.mirror(shape)),
            "keys": keys(cmap[shape]),
            "bits": bits(cmap[shape]),
        })

    # Only the Series 3 patterns the theory can actually produce.  'ou' has no
    # plain form, since it always closes the word, so that chord stays spare.
    for pat, (ident, ending) in F.SERIES3.items():
        c = F.VOWEL_IDENTITY[ident] + (F.END_MARKER if ending else "")
        out["inner_right"].append({
            "michela": pat, "vowel": ident, "ends_word": ending,
            "keys": keys(c), "bits": bits(c),
        })

    for pat, _ in f2.most_common():
        out["inner_left"].append({
            "michela": pat,
            "spells": theory.SECOND[pat],
            "is_vowel_too": theory.MIRRORED_VOWEL.get(pat),
            "keys": keys(s2map[pat]),
            "bits": bits(s2map[pat]),
        })

    # Commands sit on chords that are unassigned *within their own group*, so
    # no syllable can ever produce them.  Shapes that merely happen to be
    # unattested in the corpus are not safe enough for this.
    for name, chord, hand, why in (
        ("dosh_oneshot", "iSpBk", "left",
         "spare Series 2 chord; right hand carries the Dosh chord"),
        ("dosh_toggle", "eiSpBk", "left",
         "spare Series 2 chord, and unmapped as 0x388 in Dosh, so one shape does both"),
        ("capitalise_next", "eiSp", "right",
         "spare Series 3 chord: plain 'ou', which never occurs since ou always closes"),
        ("space", "Bk", "right",
         "spare Series 3 chord: the word-end marker with no vowel"),
        ("undo", "aostn", "left",
         "the one spare outer chord; deliberately expensive"),
    ):
        out["commands"].append({
            "name": name, "hand": hand, "why": why,
            "keys": keys(chord), "bits": bits(chord),
        })

    path = "../docs/orsy/orsy-mapping.json"
    with open(path, "w") as fp:
        json.dump(out, fp, indent=2, sort_keys=False)
        fp.write("\n")
    print(f"wrote {path}: {len(out['outer'])} outer, "
          f"{len(out['inner_right'])} inner-right, {len(out['inner_left'])} inner-left, "
          f"{len(out['commands'])} commands")
    # Sanity: no duplicate bit patterns within a group.
    for group in ("outer", "inner_right", "inner_left"):
        seen = collections.Counter(e["bits"] for e in out[group])
        dup = [b for b, n in seen.items() if n > 1]
        assert not dup, f"{group} has duplicate chords: {[hex(b) for b in dup]}"
    # A command must be free in the groups on its own hand; the other hand is
    # a different keyboard half and cannot collide.
    per_hand = {
        "left": {e["bits"] for e in out["inner_left"]},
        "right": {e["bits"] for e in out["inner_right"]},
    }
    outer_bits = {e["bits"] for e in out["outer"]}
    for c in out["commands"]:
        hand = c["hand"]
        clash = c["bits"] in outer_bits or c["bits"] in per_hand[hand]
        assert not clash, f"command {c['name']} clashes on the {hand} hand"
    print("no duplicate chords within any group; no command clashes on its own hand")


if __name__ == "__main__":
    sys.exit(main())
