import XCTest
@testable import TaipoKit

/// The Swift chord engine has to agree with the Rust one, chord for chord.
///
/// `bbq-keyboard/tests/golden/*.log` and `*.derived` are generated by the Rust replay from
/// synthetic logs and checked in; they are copied here verbatim.  This is the mechanism
/// taipo-teacher.md phase 4 names for keeping a second implementation of the engine from
/// drifting: not review, not care, but a test that fails.
///
/// Only the `chord` lines are compared.  The Swift side deliberately does not port the
/// modifier state machine or `type_text`, because the trainer knows the target text and
/// sees what was actually typed through its own key events -- it needs to know which chord
/// on which hand, not what the firmware did with it afterwards.
final class GoldenTests: XCTestCase {

    private func layouts() throws -> Layouts {
        try Layouts.bundled()
    }

    private func golden(_ name: String, _ ext: String) throws -> String {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "golden/\(name)", withExtension: ext),
            "golden/\(name).\(ext) missing")
        return try String(contentsOf: url, encoding: .utf8)
    }

    /// Replay one golden log and return the chord lines this engine produces.
    private func chordLines(_ name: String) throws -> [String] {
        let engine = ChordEngine(layouts: try layouts())
        var out = [String]()

        for line in try golden(name, "log").split(separator: "\n") {
            let text = line.trimmingCharacters(in: .whitespaces)
            if text.isEmpty || text.hasPrefix("#") { continue }
            let fields = text.split(separator: " ").map(String.init)

            // `0 = variant 0`: which table the log was typed in.  Acted on, not skipped --
            // the fixture says so precisely because neither engine should be guessing, and
            // the Rust side that wrote it replayed it in the table named here.
            if fields.count == 4, fields[1] == "=" {
                if let value = UInt8(fields[3]) {
                    engine.marker(fields[2], value: value)
                }
                continue
            }
            guard fields.count == 3 else { continue }
            guard let time = UInt32(fields[0]) else { continue }
            let press = fields[1] == "+"
            guard let key = keyCode(fields[2], try layouts()) else { continue }
            for chord in engine.feed(key: key, press: press, timeMs: time) {
                out.append(engine.describe(chord))
            }
        }
        for chord in engine.finish() {
            out.append(engine.describe(chord))
        }
        return out
    }

    /// `L.t` and `R.Sp` back to a key code, by searching the scan map the same way
    /// `bbq_keyboard::replay::key_for_name` does.
    private func keyCode(_ name: String, _ layouts: Layouts) -> Int? {
        if name.hasPrefix("k") { return Int(name.dropFirst()) }
        let parts = name.split(separator: ".")
        guard parts.count == 2 else { return nil }
        let wantSide = parts[0] == "L" ? "left" : "right"
        let wantName = String(parts[1])
        return layouts.scanMap.upper.first {
            $0.side == wantSide && $0.name == wantName
        }?.key
    }

    /// The chord lines from the checked-in derived file.
    private func expectedChords(_ name: String) throws -> [String] {
        try golden(name, "derived")
            .split(separator: "\n")
            .filter { $0.hasPrefix("chord ") }
            .map { String($0.dropFirst("chord ".count)) }
    }

    private func compare(_ name: String) throws {
        let got = try chordLines(name)
        let want = try expectedChords(name)
        XCTAssertEqual(got.count, want.count, "\(name): chord count differs")
        for (i, (g, w)) in zip(got, want).enumerated() {
            XCTAssertEqual(g, w, "\(name): chord \(i) differs")
        }
    }

    /// Clean typing: every chord tapped and released, hands alternating.
    func testCleanLogMatchesRust() throws {
        try compare("clean")
    }

    /// Sloppy typing: same-hand runs, spelled grams, split chords and corrections.  This is
    /// the one that exercises rollover and the window expiring mid-chord.
    func testSloppyLogMatchesRust() throws {
        try compare("sloppy")
    }

    /// A writer whose fingers land on the wrong row and on the wrong finger.
    func testSlipsLogMatchesRust() throws {
        try compare("slips")
    }

    /// The tables the app resolves chords with must be the ones the keyboard is running,
    /// or every chord it names is a plausible lie.  The device reports this in `Hello`.
    func testFingerprintIsReadable() throws {
        let l = try layouts()
        XCTAssertNotNil(l.fingerprintValue)
        XCTAssertEqual(l.scancodeSet, "proto3")
        XCTAssertGreaterThan(l.variants["taipo"]?.chords.count ?? 0, 100)
        XCTAssertGreaterThan(l.variants["dosh"]?.chords.count ?? 0, 100)
    }
}

/// Live behaviour, which the golden files cannot cover: they are finished logs, and every
/// chord in them is followed by another event.
final class LiveTests: XCTestCase {

    private func engine() throws -> ChordEngine {
        ChordEngine(layouts: try Layouts.bundled())
    }

    /// A chord held past the window commits on the timer, and needs the clock moved for
    /// that to happen.  Seven chords in ten end this way in real typing, so an engine that
    /// only advances on key events shows the display a chord behind.
    func testHeldChordCommitsWhenTimeAdvances() throws {
        let e = try engine()
        // `L.t` is key 6 in the upper scan map; press it and hold.
        let key = try XCTUnwrap(
            (try Layouts.bundled()).scanMap.upper.first { $0.side == "left" && $0.name == "t" }?.key)

        XCTAssertTrue(e.feed(key: key, press: true, timeMs: 1000).isEmpty,
                      "nothing commits while the window is open")
        XCTAssertTrue(e.advance(toMs: 1050).isEmpty, "still open at 50ms")

        let committed = e.advance(toMs: 1200)
        XCTAssertEqual(committed.count, 1, "the window should have expired")
        XCTAssertEqual(committed.first?.end, .timerExpired)
        XCTAssertEqual(committed.first?.timeMs, 1099, "first + window - 1")
    }

    /// A tapped chord needs no help: it commits on the release of its last key.
    func testTappedChordCommitsOnRelease() throws {
        let e = try engine()
        let key = try XCTUnwrap(
            (try Layouts.bundled()).scanMap.upper.first { $0.side == "left" && $0.name == "t" }?.key)

        XCTAssertTrue(e.feed(key: key, press: true, timeMs: 1000).isEmpty)
        let committed = e.feed(key: key, press: false, timeMs: 1040)
        XCTAssertEqual(committed.count, 1)
        XCTAssertEqual(committed.first?.end, .allReleased)
    }
}
