import XCTest
@testable import TaipoKit

/// The Swift chord engine has to agree with the Rust one, chord for chord.
///
/// `bbq-keyboard/tests/golden/*.log` and `*.derived` are generated by the Rust replay from
/// synthetic logs and checked in; they are copied here verbatim.  This is the mechanism
/// taipo-teacher.md phase 4 names for keeping a second implementation of the engine from
/// drifting: not review, not care, but a test that fails.
///
/// Only the `chord` lines are compared.  The Swift side deliberately does not port the
/// modifier state machine or `type_text`, because the trainer knows the target text and
/// sees what was actually typed through its own key events -- it needs to know which chord
/// on which hand, not what the firmware did with it afterwards.
final class GoldenTests: XCTestCase {

    private func layouts() throws -> Layouts {
        try Layouts.bundled()
    }

    private func golden(_ name: String, _ ext: String) throws -> String {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "golden/\(name)", withExtension: ext),
            "golden/\(name).\(ext) missing")
        return try String(contentsOf: url, encoding: .utf8)
    }

    /// Replay one golden log and return the chord lines this engine produces.
    private func chordLines(_ name: String) throws -> [String] {
        let engine = ChordEngine(layouts: try layouts())
        var out = [String]()

        for line in try golden(name, "log").split(separator: "\n") {
            let text = line.trimmingCharacters(in: .whitespaces)
            if text.isEmpty || text.hasPrefix("#") { continue }
            let fields = text.split(separator: " ").map(String.init)
            guard fields.count == 3 else { continue }

            if fields[1] == "=" {
                continue  // markers carry no key
            }
            guard let time = UInt32(fields[0]) else { continue }
            let press = fields[1] == "+"
            guard let key = keyCode(fields[2], try layouts()) else { continue }
            for chord in engine.feed(key: key, press: press, timeMs: time) {
                out.append(engine.describe(chord))
            }
        }
        for chord in engine.finish() {
            out.append(engine.describe(chord))
        }
        return out
    }

    /// `L.t` and `R.Sp` back to a key code, by searching the scan map the same way
    /// `bbq_keyboard::replay::key_for_name` does.
    private func keyCode(_ name: String, _ layouts: Layouts) -> Int? {
        if name.hasPrefix("k") { return Int(name.dropFirst()) }
        let parts = name.split(separator: ".")
        guard parts.count == 2 else { return nil }
        let wantSide = parts[0] == "L" ? "left" : "right"
        let wantName = String(parts[1])
        return layouts.scanMap.upper.first {
            $0.side == wantSide && $0.name == wantName
        }?.key
    }

    /// The chord lines from the checked-in derived file.
    private func expectedChords(_ name: String) throws -> [String] {
        try golden(name, "derived")
            .split(separator: "\n")
            .filter { $0.hasPrefix("chord ") }
            .map { String($0.dropFirst("chord ".count)) }
    }

    private func compare(_ name: String) throws {
        let got = try chordLines(name)
        let want = try expectedChords(name)
        XCTAssertEqual(got.count, want.count, "\(name): chord count differs")
        for (i, (g, w)) in zip(got, want).enumerated() {
            XCTAssertEqual(g, w, "\(name): chord \(i) differs")
        }
    }

    /// Clean typing: every chord tapped and released, hands alternating.
    func testCleanLogMatchesRust() throws {
        try compare("clean")
    }

    /// Sloppy typing: same-hand runs, spelled grams, split chords and corrections.  This is
    /// the one that exercises rollover and the window expiring mid-chord.
    func testSloppyLogMatchesRust() throws {
        try compare("sloppy")
    }

    /// The tables the app resolves chords with must be the ones the keyboard is running,
    /// or every chord it names is a plausible lie.  The device reports this in `Hello`.
    func testFingerprintIsReadable() throws {
        let l = try layouts()
        XCTAssertNotNil(l.fingerprintValue)
        XCTAssertEqual(l.scancodeSet, "proto3")
        XCTAssertGreaterThan(l.variants["taipo"]?.chords.count ?? 0, 100)
        XCTAssertGreaterThan(l.variants["posh"]?.chords.count ?? 0, 100)
    }
}
