import XCTest
@testable import MinderKit

/// The Swift encoding has to be byte-for-byte what the Rust side produces.
///
/// `minder/tests/wire-vectors.txt` is generated by `minder/tests/golden.rs` and copied here
/// verbatim; a protocol change regenerates it and this fails until Swift is brought along.
/// That is the entire mechanism keeping two implementations of one protocol honest, since
/// there is no shared code between them.
final class WireVectorsTests: XCTestCase {

    /// The vectors, as name -> hex bytes.
    private func vectors() throws -> [String: [UInt8]] {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "wire-vectors", withExtension: "txt"),
            "wire-vectors.txt missing from the test bundle"
        )
        let text = try String(contentsOf: url, encoding: .utf8)

        var out = [String: [UInt8]]()
        var name: String?
        for line in text.split(separator: "\n", omittingEmptySubsequences: false) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty || trimmed.hasPrefix("#") || trimmed.hasPrefix("##") {
                continue
            }
            if !line.hasPrefix(" ") {
                name = trimmed
            } else if trimmed.hasPrefix("len ") {
                continue
            } else if let current = name {
                out[current] = hexBytes(trimmed)
                name = nil
            }
        }
        return out
    }

    private func hexBytes(_ s: String) -> [UInt8] {
        var out = [UInt8]()
        var iter = s.makeIterator()
        while let a = iter.next(), let b = iter.next() {
            out.append(UInt8(String([a, b]), radix: 16) ?? 0)
        }
        return out
    }

    private func hex(_ bytes: [UInt8]) -> String {
        bytes.map { String(format: "%02x", $0) }.joined()
    }

    private func check(_ name: String, _ request: Request, _ v: [String: [UInt8]]) throws {
        let expected = try XCTUnwrap(v[name], "no vector named \(name)")
        XCTAssertEqual(
            hex(request.encode()), hex(expected),
            "\(name) encodes differently from the Rust side"
        )
    }

    /// Every request this build can send matches its vector byte for byte.
    func testRequestsMatchVectors() throws {
        let v = try vectors()
        try check("Request::Hello", .hello(version: MinderVersion.current), v)
        try check("Request::Hello{version:\"\"}", .hello(version: ""), v)
        try check("Request::ReadFlash", .readFlash(offset: 0x1030_0000, size: 4096), v)
        try check("Request::Hash", .hash(offset: 0x1030_0000, size: 4096), v)
        try check("Request::Reset", .reset, v)
        try check("Request::GetEvent", .getEvent(timeoutMs: 5000), v)
        try check("Request::TestEvent", .testEvent(count: 3, delayMs: 500), v)
        try check("Request::Program{data:[]}", .program(offset: 0x1030_0000, data: []), v)
        try check(
            "Request::Program{54 bytes} (exactly one packet)",
            .program(offset: 0x1030_0000, data: Array(repeating: 0xab, count: 54)), v)
        try check(
            "Request::Program{118 bytes} (whole packets)",
            .program(offset: 0x1030_0000, data: Array(repeating: 0xab, count: 118)), v)
        try check(
            "Request::Program{100 bytes}",
            .program(offset: 0x1030_0000, data: Array(repeating: 0xab, count: 100)), v)
        try check("Request::SetLogging", .setLogging(enabled: true, watermark: 1), v)
        try check("Request::GetEventLog", .getEventLog(maxBytes: 4000), v)
        try check("Request::EventLogAck", .eventLogAck(throughSeq: 12345), v)
    }

    /// The leading null is the thing a generic CBOR encoder gets wrong, so it gets its own
    /// test rather than only being implied by the vector comparison above.
    func testFieldOneProducesALeadingNull() {
        let bytes = Request.hello(version: "").encode()
        XCTAssertEqual(Array(bytes.prefix(4)), [0x82, 0x01, 0x82, 0xf6],
                       "array(2), variant 1, array(2), null -- version is #[n(1)]")
    }

    /// Replies decode, including the fields a `Vec<u8>` and a `ByteVec` encode differently.
    func testRepliesDecode() throws {
        let v = try vectors()

        guard case .hello(let hello) = try Reply.decode(v["Reply::Hello (current firmware)"]!)
        else { return XCTFail("not a Hello") }
        XCTAssertEqual(hello.version, "2026-08-30a")
        XCTAssertEqual(hello.bootID, 0x0123_4567_89ab_cdef)
        XCTAssertEqual(hello.layoutFingerprint, 0xeef6_b320_a04a_3492)
        XCTAssertEqual(hello.capabilities, ["events", "test-events", "flash"])

        // `Vec<u8>` comes over as an array of integers, `ByteVec` as a byte string; both
        // have to read back as bytes.
        guard case .flashData(let offset, let data) = try Reply.decode(v["Reply::FlashData"]!)
        else { return XCTFail("not FlashData") }
        XCTAssertEqual(offset, 0x1030_0000)
        XCTAssertEqual(data, [1, 2, 3])

        guard case .hash(let hash) = try Reply.decode(v["Reply::Hash"]!) else {
            return XCTFail("not a Hash")
        }
        XCTAssertEqual(hash.count, 32)

        XCTAssertEqual(try Reply.decode(v["Reply::NoEvent"]!), .noEvent)
        XCTAssertEqual(try Reply.decode(v["Reply::Ok"]!), .ok)
        XCTAssertEqual(try Reply.decode(v["Reply::ProgramDone"]!), .programDone)
        XCTAssertEqual(try Reply.decode(v["Reply::Reset"]!), .reset)
        XCTAssertEqual(
            try Reply.decode(v["Reply::Error"]!),
            .error("Program not on erase boundary"))

        guard case .event(let event) = try Reply.decode(v["Reply::Event"]!) else {
            return XCTFail("not an Event")
        }
        XCTAssertEqual(event, .test(seq: 1))
        guard case .event(let ready) = try Reply.decode(v["Reply::Event{LogReady}"]!) else {
            return XCTFail("not an Event")
        }
        XCTAssertEqual(ready, .logReady(pending: 64))

        guard case .eventLog(let batch) = try Reply.decode(v["Reply::EventLog (3 records)"]!)
        else { return XCTFail("not an EventLog") }
        XCTAssertEqual(batch.seq, 1000)
        XCTAssertEqual(batch.records.count, 12)
    }

    /// A `Hello` from firmware predating `boot_id` still decodes, reporting the fields it
    /// did not send as absent rather than as zero.  This is the case that decides whether a
    /// host update can talk to an unflashed keyboard.
    func testHelloFromOlderFirmware() throws {
        let v = try vectors()
        let recorded = try XCTUnwrap(v["Reply::Hello (recorded from 2024-11-01a firmware)"])
        guard case .hello(let hello) = try Reply.decode(recorded) else {
            return XCTFail("not a Hello")
        }
        XCTAssertEqual(hello.version, "2024-11-01a")
        XCTAssertEqual(hello.info, "mesa1-pnbgmlibdbijkcad")
        XCTAssertNil(hello.bootID)
        XCTAssertNil(hello.capabilities)
        XCTAssertTrue(hello.supports(Capability.flash), "predates the list, but can flash")
        XCTAssertFalse(hello.supports(Capability.events))

        // The same absence written by the current encoder is six long with trailing nulls,
        // rather than three long, and has to read the same way.
        let padded = try XCTUnwrap(v["Reply::Hello (new encoder, fields absent)"])
        guard case .hello(let same) = try Reply.decode(padded) else {
            return XCTFail("not a Hello")
        }
        XCTAssertNil(same.bootID)
        XCTAssertNil(same.capabilities)
    }

    /// An unrecognized variant is newer firmware, not a reason to fail.
    func testUnknownVariantIsReported() throws {
        // [200, []]
        let reply = try Reply.decode([0x82, 0x18, 0xc8, 0x80])
        XCTAssertEqual(reply, .unknown(index: 200))
    }
}
