//! The Taipo modifier indicator palette.
//!
//! Generated by `mod-palette.py`; do not edit.  Regenerate with:
//!     uv run --with numpy python mod-palette.py
//!
//! Each table is indexed by the bits of `Mods`, so entry 0 is unused.  The values are
//! what goes on the wire: the ws2812's PWM is linear in light, so they are linear, and
//! they are already scaled for the indicator's brightness.
//!
//! Oklab lightness 0.65 bright (all held modifiers sticky) and 0.45 dim (at least
//! one is one-shot), with the largest channel scaled to 32.

use smart_leds::RGB8;

/// A modifier indicator palette: one color per modifier set, in two lightnesses.
pub struct ModPalette {
    /// Shown when every held modifier is sticky.
    pub bright: [RGB8; 16],
    /// Shown when at least one held modifier is still one-shot.
    pub dim: [RGB8; 16],
}

/// Packed: the most separable 15 colors, which have to be learned one at a time.
///
/// Minimum Oklab distance between any two of the 31 states: 0.0796 before
/// quantization, 0.0672 after.
pub static MOD_PALETTE_PACKED: ModPalette = ModPalette {
    bright: [
        RGB8::new(0, 0, 0),
        RGB8::new(0, 13, 0),  // C
        RGB8::new(31, 2, 0),  // S
        RGB8::new(9, 10, 0),  // C+S
        RGB8::new(2, 8, 32),  // A
        RGB8::new(1, 12, 7),  // C+A
        RGB8::new(32, 0, 6),  // S+A
        RGB8::new(10, 9, 6),  // C+S+A
        RGB8::new(20, 1, 32), // G
        RGB8::new(9, 8, 17),  // C+G
        RGB8::new(28, 0, 17), // S+G
        RGB8::new(19, 6, 0),  // C+S+G
        RGB8::new(11, 5, 32), // A+G
        RGB8::new(0, 11, 18), // C+A+G
        RGB8::new(18, 4, 17), // S+A+G
        RGB8::new(20, 5, 6),  // C+S+A+G
    ],
    dim: [
        RGB8::new(0, 0, 0),
        RGB8::new(0, 4, 0),  // C
        RGB8::new(10, 1, 0), // S
        RGB8::new(3, 3, 0),  // C+S
        RGB8::new(1, 3, 11), // A
        RGB8::new(0, 4, 2),  // C+A
        RGB8::new(11, 0, 2), // S+A
        RGB8::new(3, 3, 2),  // C+S+A
        RGB8::new(7, 0, 11), // G
        RGB8::new(3, 3, 6),  // C+G
        RGB8::new(9, 0, 6),  // S+G
        RGB8::new(6, 2, 0),  // C+S+G
        RGB8::new(4, 2, 11), // A+G
        RGB8::new(0, 4, 6),  // C+A+G
        RGB8::new(6, 1, 6),  // S+A+G
        RGB8::new(7, 2, 2),  // C+S+A+G
    ],
};

/// Sums: four base colors added together, so a combination reads as its parts.
///
/// Minimum Oklab distance between any two of the 31 states: 0.0289 before
/// quantization, 0.0257 after.
pub static MOD_PALETTE_SUMS: ModPalette = ModPalette {
    bright: [
        RGB8::new(0, 0, 0),
        RGB8::new(14, 9, 0),  // C
        RGB8::new(31, 2, 3),  // S
        RGB8::new(26, 4, 0),  // C+S
        RGB8::new(23, 2, 21), // A
        RGB8::new(21, 5, 11), // C+A
        RGB8::new(32, 0, 13), // S+A
        RGB8::new(29, 2, 8),  // C+S+A
        RGB8::new(7, 11, 7),  // G
        RGB8::new(11, 10, 2), // C+G
        RGB8::new(21, 5, 4),  // S+G
        RGB8::new(21, 6, 2),  // C+S+G
        RGB8::new(16, 6, 15), // A+G
        RGB8::new(17, 6, 10), // C+A+G
        RGB8::new(25, 3, 11), // S+A+G
        RGB8::new(25, 4, 7),  // C+S+A+G
    ],
    dim: [
        RGB8::new(0, 0, 0),
        RGB8::new(5, 3, 0),  // C
        RGB8::new(10, 1, 1), // S
        RGB8::new(9, 1, 0),  // C+S
        RGB8::new(8, 1, 7),  // A
        RGB8::new(7, 1, 4),  // C+A
        RGB8::new(11, 0, 4), // S+A
        RGB8::new(10, 1, 3), // C+S+A
        RGB8::new(2, 4, 2),  // G
        RGB8::new(4, 3, 1),  // C+G
        RGB8::new(7, 2, 1),  // S+G
        RGB8::new(7, 2, 0),  // C+S+G
        RGB8::new(5, 2, 5),  // A+G
        RGB8::new(6, 2, 3),  // C+A+G
        RGB8::new(9, 1, 4),  // S+A+G
        RGB8::new(8, 1, 2),  // C+S+A+G
    ],
};
