import Foundation

/// The Orsy word table: every word of the word list the rules can spell, with its cheapest
/// division into strokes and the patterns it needs, and the lesson plan.
///
/// Generated by `bbq-orsy/examples/lessons.rs` from the same word list the other drills
/// draw on, and bundled, so that this side never needs the inverse of the theory -- text
/// to stroke -- which is a search over 170,000 strokes.  The forward direction, stroke to
/// text, is `OrsyTheory`.  The lesson plan is here too, as pattern keys, so the ladder and
/// the printed drill sheets cannot disagree about the order.
public struct OrsyWords: Decodable {
    public struct Word: Decodable, Sendable {
        /// The word.
        public let text: String
        /// Its fewest-stroke division, as (left, right) key masks.
        public let strokes: [(UInt16, UInt16)]
        /// Every pattern and rule key any of its strokes uses.
        public let patterns: Set<String>

        enum CodingKeys: String, CodingKey {
            case text = "w"
            case strokes = "s"
            case patterns = "p"
        }

        public init(from decoder: Decoder) throws {
            let c = try decoder.container(keyedBy: CodingKeys.self)
            text = try c.decode(String.self, forKey: .text)
            strokes = try c.decode([[UInt16]].self, forKey: .strokes).map { ($0[0], $0[1]) }
            patterns = Set(try c.decode([String].self, forKey: .patterns))
        }
    }

    public struct Lesson: Decodable, Sendable {
        public let name: String
        public let title: String
        public let note: String
        /// Each item's pattern keys: an outer shape is its onset and coda readings.
        public let items: [[String]]
    }

    public let lessons: [Lesson]
    /// Most frequent first.
    public let words: [Word]

    public static func load(from url: URL) throws -> OrsyWords {
        try JSONDecoder().decode(OrsyWords.self, from: Data(contentsOf: url))
    }

    public static func bundled() throws -> OrsyWords {
        guard let url = Bundle.module.url(forResource: "orsy-words", withExtension: "json")
        else { throw LayoutsError.notBundled }
        return try load(from: url)
    }

    /// The word, if the table has it.
    public func word(_ text: String) -> Word? {
        words.first { $0.text == text }
    }
}
