
# target := "pimoroni_tiny_2040"
target := "sparkfun_pro_micro_rp2040"

srcdir := `pwd`

build:
	rm -rf build
	west build \
		--board {{target}} \
		-- \
		-DBOARD_FLASH_RUNNER=jlink \
		-DBOARD_DEBUG_RUNNER=jlink \
		-DSHIELD=proto2 \
		-DEXTRA_ZEPHYR_MODULES={{srcdir}}/bbqboards \
		#
	echo Done

jlink:
	west debugserver

gdb:
	TERM=xterm arm-zephyr-eabi-gdb "build/zephyr/zephyr.elf"

rtt:
	socat - TCP4:localhost:19021
