
target := "sparkfun_pro_micro_rp2040"
shield := "proto2"

#target := "pimoroni_tiny_2040"
#shield := "proto4"

srcdir := `pwd`

build:
	rm -rf build
	west build \
		--board {{target}} \
		-- \
		-DBOARD_FLASH_RUNNER=jlink \
		-DBOARD_DEBUG_RUNNER=jlink \
		-DSHIELD={{shield}} \
		-DEXTRA_ZEPHYR_MODULES={{srcdir}}/bbqboards \
		-DCONFIG_COMPILER_SAVE_TEMPS=y \
		#
	echo Done

jlink:
	west debugserver

gdb:
	TERM=xterm arm-zephyr-eabi-gdb "build/zephyr/zephyr.elf"

rtt:
	socat - TCP4:localhost:19021
