[package]
name = "bbq-steno"
version = "0.1.0"
edition = "2021"
default-run = "bbq-build"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bbq-build"
path = "src/bin/bbq-build.rs"

[dependencies]
defmt = "0.3"
arrayvec = { version = "0.7", default-features = false }
safe-regex = "0.2.5"

# Dependencies for 'std', which is how the binaries are build.
clap = { version = "4.0", features = ["derive"], optional = true }
anyhow = { version = "1.0.75", optional = true }
regex = { version = "=1.10.6", optional = true }

[dev-dependencies]
env_logger = "0.10.0"
log = "0.4.20"
bbq-steno-macros = { version = "0.1", path = "../bbq-steno-macros" }
anyhow = "1.0.75"
serde_json = "1.0.107"

[features]
default = ["std"]
std = ["dep:clap", "dep:anyhow", "dep:regex"]

# Optimize the tests so they don't take too long
[profile.test]
opt-level = 3
