[package]
name = "bbq-steno"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defmt = "0.3"
arrayvec = { version = "0.7", default-features = false }

[dev-dependencies]
env_logger = "0.10.0"
log = "0.4.20"
bbq-steno-macros = { version = "0.1", path = "../bbq-steno-macros" }
anyhow = "1.0.75"
serde_json = "1.0.107"

[features]
default = ["std"]
std = []

# Optimize the tests so they don't take too long
[profile.test]
opt-level = 3
