[package]
name = "bbq-steno-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bbq-steno = { version = "0.1.0", path = "../bbq-steno" }
quote = "1.0.33"
syn = "2.0.38"

[lib]
proc-macro = true
