
# The proto2 is a 30-key built around the sparkfun pro micro rp2040, one on each side.
# target := "sparkfun_pro_micro_rp2040"
# shield := "proto2"
# flags := ""

# The proto3 is a 30-key split built around the sparkfun_pro_micro_rp2040.
# target := "sparkfun_pro_micro_rp2040"
# shield := "proto3"
# flags := ""

# The proto4 is a 30-key built around the pimoroni tiny 2040 board.
# target := "pimoroni_tiny_2040"
# shield := "proto4"
# flags := "-DCONFIG_JOLT_INTER=n"

# The highboard is a 42-key semi-hand-wired board built around the Adafruit Feather RP2040
# target := "adafruit_feather_rp2040"
# shield := "highboard"
# flags := "-DCONFIG_JOLT_INTER=n"

# The jolt1 is a 42-key built around the pimoroni tiny 2040 board.
# target := "pimoroni_tiny_2040"
# shield := "jolt1"
# flags := "-DCONFIG_JOLT_INTER=y"

# The jolt2 is a 42-key built around the pimoroni tiny 2040 board.
# It has columns staggered along both Y and Z.
# target := "pimoroni_tiny_2040"
# shield := "jolt2"
# flags := "-DCONFIG_JOLT_INTER=y"

# The jolt2dir is similar to the jolt2, but instead of actually using the pimoroni, the rp2040 is
# designed directly on to the board.  It is largely the same, but with different gpio pin mappings.
# Also, it has ws2812 leds on it instead of the discrete RGB on the Pimoroni board.
# target := "pimoroni_tiny_2040"
# shield := "jolt2dir"
# flags := "-DCONFIG_JOLT_INTER=y"

# The jolt3_mez_2040 is a mezzanine board for the jolt3 built around the rp2040. We start with the
# Pimoroni, as it is a minimalist board.
target := "pimoroni_tiny_2040"
shield := "jolt3_mez_2040"
flags := "-DCONFIG_JOLT_INTER=y"

toolopt := "--tool-opt=\"/Applications/SEGGER/JLink/GDBServer/RTOSPlugin_Zephyr.dylib\""

srcdir := `pwd`

build:
	rm -rf build
	west build \
		--board {{target}} \
		-- \
		{{flags}} \
		-DBOARD_FLASH_RUNNER=jlink \
		-DBOARD_DEBUG_RUNNER=jlink \
		-DSHIELD={{shield}} \
		-DEXTRA_ZEPHYR_MODULES={{srcdir}}/bbqboards \
		-DCONFIG_COMPILER_SAVE_TEMPS=y \
		#
	echo Done

serve:
	west debugserver

gdb:
	TERM=xterm arm-zephyr-eabi-gdb "build/zephyr/zephyr.elf"

rtt:
	socat - TCP4:localhost:19021

uart0:
	picocom -l /dev/cu.usbmodem11401 -b 115200 -e e

uart1:
	picocom -l /dev/cu.usbmodem11404 -b 115200 -e e

clean:
	rm -rf build
