CONFIG_RUST=y
CONFIG_RUST_ALLOC=y

CONFIG_MAIN_STACK_SIZE=8192

CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_HID_SUPPORT=y
CONFIG_LED=y
CONFIG_PWM=y

CONFIG_SAMPLE_USBD_MANUFACTURER="BBQ"
CONFIG_SAMPLE_USBD_PRODUCT="Jolt Keyboard"
CONFIG_SAMPLE_USBD_VID=0x2FE3
CONFIG_SAMPLE_USBD_PID=0x4201
CONFIG_SAMPLE_USBD_MAX_POWER=125

# Enable the Segger console.
CONFIG_USE_SEGGER_RTT=y

# Use the RTT Console
CONFIG_UART_CONSOLE=n
CONFIG_RTT_CONSOLE=y
