//! Golden byte vectors for the minder wire format.
//!
//! `taipo-teacher.md` phase 1d: the Swift trainer speaks minder itself, so
//! `minder/src/lib.rs` stops being the only definition of the protocol and starts being
//! the *reference* one.  This file is what keeps a second implementation honest.
//!
//! It matters more than it sounds, because the framing is not the one a CBOR library
//! reaches for on its own.  minicbor writes a variant as
//!
//! ```text
//! [ variant index, [ field 0, field 1, ... ] ]
//! ```
//!
//! where the inner array is **positional** and every field number that is not used is
//! filled with `null`.  `#[n(1)]` on the first field therefore produces a leading `f6`,
//! not a one-element array.  An encoder emitting the natural `[1, ["2024-11-01a"]]` is
//! valid CBOR and will be rejected by the device.
//!
//! The cases deliberately include the packet-economics ones, because the bulk transport
//! ends a message at the first packet shorter than 64 bytes:
//!
//! - a message shorter than one packet,
//! - one that is exactly 64 bytes, which needs a zero-length packet after it,
//! - one that spans several packets,
//! - one whose total is again an exact multiple of 64.
//!
//! The 64-byte case is not hypothetical.  `VendorMinder::send` used to omit the
//! zero-length packet, and on hardware the device then returned no reply at all and
//! swallowed the following request as a continuation of the stuck one.
//!
//! Regenerate after a deliberate protocol change with
//!
//! ```sh
//! cd minder && UPDATE_GOLDEN=1 cargo test --test golden
//! ```
//!
//! and read the diff before committing it.  A line changing here means every other
//! implementation of the protocol has to change too.

use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use minder::keylog::{Delta, Marker, Record};
use minder::{cap, Event, Reply, Request, PACKET_SIZE};

fn hex(bytes: &[u8]) -> String {
    bytes.iter().fold(String::new(), |mut s, b| {
        let _ = write!(s, "{b:02x}");
        s
    })
}

/// One vector: a name, the encoding, and what the transport has to do with it.
fn vector<T: minicbor::Encode<()>>(out: &mut String, name: &str, value: &T) {
    let mut buf = Vec::new();
    minicbor::encode(value, &mut buf).expect("encode");
    let packets = buf.len().div_ceil(PACKET_SIZE).max(1);
    let zlp = buf.len() % PACKET_SIZE == 0;
    let _ = writeln!(
        out,
        "{name}\n  len {len}  packets {packets}  trailing-zlp {zlp}\n  {hex}",
        len = buf.len(),
        hex = hex(&buf),
    );
}

fn vectors() -> String {
    let mut out = String::new();
    out.push_str(
        "# minder wire format golden vectors.\n\
         # Generated by minder/tests/golden.rs; regenerate with\n\
         #   cd minder && UPDATE_GOLDEN=1 cargo test --test golden\n\
         # trailing-zlp true means the sender must follow the payload with a\n\
         # zero-length packet, or the receiver waits for a continuation forever.\n\n",
    );

    out.push_str("## Requests\n\n");
    vector(&mut out, "Request::Hello", &Request::Hello { version: minder::VERSION.into() });
    vector(&mut out, "Request::Hello{version:\"\"}", &Request::Hello { version: String::new() });
    vector(&mut out, "Request::ReadFlash", &Request::ReadFlash { offset: 0x1030_0000, size: 4096 });
    vector(&mut out, "Request::Hash", &Request::Hash { offset: 0x1030_0000, size: 4096 });
    vector(&mut out, "Request::Reset", &Request::Reset);
    vector(&mut out, "Request::GetEvent", &Request::GetEvent { timeout_ms: 5000 });
    vector(&mut out, "Request::TestEvent", &Request::TestEvent { count: 3, delay_ms: 500 });
    vector(&mut out, "Request::Program{data:[]}", &Request::Program { offset: 0x1030_0000, data: Vec::new().into() });

    // The packet-boundary cases, found rather than guessed: the first payload size whose
    // encoding is exactly one packet, and the first that is an exact multiple of packets.
    let program = |n: usize| Request::Program { offset: 0x1030_0000, data: vec![0xab; n].into() };
    let encoded_len = |n: usize| {
        let mut b = Vec::new();
        minicbor::encode(&program(n), &mut b).expect("encode");
        b.len()
    };
    if let Some(n) = (1..=4096).find(|&n| encoded_len(n) == PACKET_SIZE) {
        vector(&mut out, &format!("Request::Program{{{n} bytes}} (exactly one packet)"), &program(n));
    }
    if let Some(n) = (1..=4096).find(|&n| encoded_len(n) > PACKET_SIZE && encoded_len(n) % PACKET_SIZE == 0) {
        vector(&mut out, &format!("Request::Program{{{n} bytes}} (whole packets)"), &program(n));
    }
    vector(&mut out, "Request::Program{100 bytes}", &program(100));
    vector(&mut out, "Request::SetLogging", &Request::SetLogging { enabled: true, watermark: 1 });
    vector(&mut out, "Request::GetEventLog", &Request::GetEventLog { max_bytes: 4000 });
    vector(&mut out, "Request::EventLogAck", &Request::EventLogAck { through_seq: 12345 });

    out.push_str("\n## Replies\n\n");
    vector(
        &mut out,
        "Reply::Hello (current firmware)",
        &Reply::Hello {
            version: "2026-08-30a".into(),
            info: "mesa1-pnbgmlibdbijkcad".into(),
            boot_id: Some(0x0123_4567_89ab_cdef),
            layout_fingerprint: Some(0xeef6_b320_a04a_3492),
            capabilities: Some(vec![
                cap::EVENTS.into(),
                cap::TEST_EVENTS.into(),
                cap::FLASH.into(),
            ]),
        },
    );
    // Encoded by *this* crate with the fields absent, which still writes the full
    // positional array and fills the gaps with null.  It is not what old firmware sends;
    // that is the recorded case below, and a decoder has to accept both.
    vector(
        &mut out,
        "Reply::Hello (new encoder, fields absent)",
        &Reply::Hello {
            version: "2024-11-01a".into(),
            info: "mesa1-pnbgmlibdbijkcad".into(),
            boot_id: None,
            layout_fingerprint: None,
            capabilities: None,
        },
    );
    // Recorded from a mesa1 running the 2024-11-01a firmware.  The inner array is 3
    // long rather than 6, because the fields did not exist yet; this is the shape a
    // decoder meets in the field, and `tests_bulk` asserts it still decodes.
    let recorded: &[u8] = &[
        0x82, 0x01, 0x83, 0xf6, 0x6b, 0x32, 0x30, 0x32, 0x34, 0x2d, 0x31, 0x31, 0x2d, 0x30, 0x31,
        0x61, 0x76, 0x6d, 0x65, 0x73, 0x61, 0x31, 0x2d, 0x70, 0x6e, 0x62, 0x67, 0x6d, 0x6c, 0x69,
        0x62, 0x64, 0x62, 0x69, 0x6a, 0x6b, 0x63, 0x61, 0x64,
    ];
    let _ = writeln!(
        out,
        "Reply::Hello (recorded from 2024-11-01a firmware)\n  \
         len {}  packets 1  trailing-zlp false\n  {}",
        recorded.len(),
        hex(recorded),
    );

    vector(&mut out, "Reply::Log", &Reply::Log { message: "hi".into() });
    vector(&mut out, "Reply::FlashData", &Reply::FlashData { offset: 0x1030_0000, data: vec![1, 2, 3] });
    vector(&mut out, "Reply::Hash", &Reply::Hash { hash: [0x5a; 32].into() });
    vector(&mut out, "Reply::ProgramDone", &Reply::ProgramDone);
    // Event is the protocol's first nested enum, and worth its own vector: a Swift
    // library has to frame the inner variant the same way as the outer one.
    vector(&mut out, "Reply::Event", &Reply::Event { event: Event::Test { seq: 1 } });
    vector(&mut out, "Reply::Event{LogReady}", &Reply::Event { event: Event::LogReady { pending: 64 } });
    vector(&mut out, "Reply::NoEvent", &Reply::NoEvent);
    {
        // A short, hand-built batch: a press, its release, and a variant switch.  Spelling
        // the records out here rather than capturing them from a device keeps this a test
        // of the encoding rather than of whatever the keyboard happened to be doing.
        let mut records = Vec::new();
        for rec in [
            Record::key(Delta::from_millis(0), 5, true),
            Record::key(Delta::from_millis(42), 5, false),
            Record::marker(Delta::from_millis(1500), Marker::Variant, 1),
        ] {
            records.extend_from_slice(&rec.encode());
        }
        vector(
            &mut out,
            "Reply::EventLog (3 records)",
            &Reply::EventLog {
                boot_id: 0x0123_4567_89ab_cdef,
                seq: 1000,
                dropped: 0,
                anchor_ms: 7,
                records: records.into(),
                remaining: 0,
            },
        );
    }
    vector(&mut out, "Reply::Ok", &Reply::Ok);
    vector(&mut out, "Reply::Error", &Reply::Error { text: "Program not on erase boundary".into() });
    vector(&mut out, "Reply::Reset", &Reply::Reset);

    out
}

fn golden_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/wire-vectors.txt")
}

/// The checked-in vectors match what the crate encodes today.
#[test]
fn test_wire_vectors_current() {
    let produced = vectors();
    let path = golden_path();

    if std::env::var_os("UPDATE_GOLDEN").is_some() {
        fs::write(&path, &produced).expect("write golden");
        return;
    }

    let committed = fs::read_to_string(&path).unwrap_or_default();
    if produced != committed {
        let first = produced
            .lines()
            .zip(committed.lines())
            .enumerate()
            .find(|(_, (a, b))| a != b)
            .map(|(n, (a, b))| format!("line {}:\n  produced:  {a}\n  committed: {b}", n + 1))
            .unwrap_or_else(|| "the files agree line for line, but one is longer".into());
        panic!(
            "minder/tests/wire-vectors.txt is stale.  A change here changes the wire \
             format, and every other implementation of the protocol with it.\n\
             Regenerate with\n    cd minder && UPDATE_GOLDEN=1 cargo test --test golden\n{first}"
        );
    }
}

/// Every vector decodes back to what produced it.
///
/// The vectors would otherwise only pin the encoder, and an encoder and decoder can
/// agree with each other while both being wrong about the format.
#[test]
fn test_vectors_round_trip() {
    let requests = [
        Request::Hello { version: minder::VERSION.into() },
        Request::Hash { offset: 0x1030_0000, size: 4096 },
        Request::Reset,
        Request::GetEvent { timeout_ms: 5000 },
        Request::TestEvent { count: 3, delay_ms: 500 },
        Request::Program { offset: 0x1030_0000, data: vec![0xab; 100].into() },
    ];
    for req in &requests {
        let mut buf = Vec::new();
        minicbor::encode(req, &mut buf).expect("encode");
        let back: Request = minicbor::decode(&buf).expect("decode");
        assert_eq!(&back, req);
    }
}
