#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Build MonkeyType practice lists for the n-gram chords in `TAIPO_ACTIONS`.

The grams and their order come from the chord table itself, so the drills stay
in step with the firmware: the table is written easiest chord first, which is
also the order they are worth learning in.

Nothing outside the keyboard can tell whether a word was typed with its chord
or spelled out letter by letter, so the lists do the enforcing instead.  A word
belongs to lesson `g` only when *g alone* segments it as cheaply as all
thirteen chords together:

    cost(word, {g}) == cost(word, all grams)

and the chords learned before it do not already type the word that cheaply:

    cost(word, learned before g) > cost(word, learned including g)

The first rule keeps out words that want a chord you have not learned yet --
`nation` is a `tion` word and never an `on` word, because `n a tion` beats
`n a t i on`.  The second keeps out words where a chord you already have does
the same job: `more` is not an `or` word, because `m o re` costs what `m or e`
does and `re` came first.  Between them, every optimal way to type a lesson
word uses that lesson's chord.

Review lists relax that to the grams learned so far, and round-robin over them
so each chord in the set gets a turn.

Usage:
    uv run words/drills.py                     # markdown, all lessons
    uv run words/drills.py -n 50 --review 3
    uv run words/drills.py --lesson the        # one list, bare words
"""

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

# MonkeyType's own list, so the drills are drawn from the vocabulary the
# practice is done in.  Ignored by git and fetched on first use, as
# `ngrams.py` does with the Norvig corpus.
WORDS_URL = ("https://raw.githubusercontent.com/monkeytypegame/monkeytype/"
             "master/frontend/static/languages/english_10k.json")
DEFAULT_WORDS = Path(__file__).with_name("english_10k.json")
DEFAULT_TABLE = (Path(__file__).parent.parent
                 / "bbq-keyboard" / "src" / "layout" / "taipo.rs")

MIN_LEN = 2
WRAP = 88


PREAMBLE = """# Taipo n-gram drills

Practice lists for the n-gram chords, one lesson per chord, generated by
`words/drills.py` from the {count} `Action::Text` entries in `TAIPO_ACTIONS`.
The table is written easiest chord first, which is also the order they are
worth learning in, so the lessons follow it.  Regenerate with:

```
uv run words/drills.py > docs/taipo-drills.md
```

See [ngrams-results.md](ngrams-results.md) for where the grams came from and
which chord each one sits on.

## How to use these

MonkeyType: **custom text**, paste a block, turn *random* on and set a word
count.  Punctuation and numbers off.  The capital lists are separate because
custom text keeps case, and a lower-case list with `Random` on will never
exercise the `+Sp` half of a chord.

Nothing outside the keyboard can see whether a word was chorded or spelled out,
so the lists do the enforcing.  A word is in lesson `g` only if two things
hold: no chord past `g` would type it any cheaper, and no chord before `g`
already does.  So while typing a lesson, **every word in front of you has
exactly one best answer and it is today's chord** -- if you spell one out you
will know, because you had no reason to be there.  `nation` is a `tion` word
and never an `on` word; `more` is not an `or` word, because `re` came first and
`m o re` already costs three.

Speed is the wrong measure at first.  A chord you have to think about is slower
than the letters it replaces, and stays slower for a while; the drill is for
the recognition, not the pace.  Watch instead for whether the gram is being
*seen* -- `otherwise` as `o-the-r-w-i-s-e` rather than nine letters.

A review list appears every {review} lessons and at the end, mixing everything
learned so far.  Those are where the chords stop being an exercise: the words
are ordinary, the grams are wherever they fall, and nothing marks them.

Each lesson's words are the most common qualifying ones from MonkeyType's
`english_10k`.  `--lesson <gram>` prints one list bare, and `-n` takes more
words per lesson if a list gets stale.
"""


def read_grams(path, table="TAIPO_ACTIONS"):
    """The `Action::Text` grams of a chord table, in table order.

    Only the lower-case entries: each gram has a `+Sp` twin typing it
    capitalised, which is the same chord and not a separate thing to learn.
    """
    source = path.read_text(encoding="utf-8")
    match = re.search(rf"static {table}[^=]*=\s*&?\[(.*?)\n\];", source, re.S)
    if not match:
        raise SystemExit(f"no table {table} found in {path}")
    grams = []
    for text in re.findall(r'action:\s*Action::Text\("([^"]+)"\)',
                           match.group(1)):
        if text.islower() and text not in grams:
            grams.append(text)
    return grams


def load_words(path, url=WORDS_URL):
    """The MonkeyType list, most frequent first, proper nouns dropped."""
    if not path.exists():
        print(f"downloading {url} -> {path}", file=sys.stderr)
        urllib.request.urlretrieve(url, path)
    data = json.loads(path.read_text(encoding="utf-8"))
    words = data["words"] if isinstance(data, dict) else data
    seen, out = set(), []
    for word in words:
        if word.isalpha() and word.islower() and word not in seen:
            seen.add(word)
            out.append(word)
    return out


def cost(word, grams, max_len):
    """Fewest chords `word` segments into, given the grams that have chords."""
    n = len(word)
    dp = [0] * (n + 1)
    for i in range(1, n + 1):
        best = dp[i - 1] + 1
        for length in range(MIN_LEN, min(max_len, i) + 1):
            if word[i - length:i] in grams and dp[i - length] + 1 < best:
                best = dp[i - length] + 1
        dp[i] = best
    return dp[n]


def segment(word, grams, max_len):
    """A cheapest segmentation, preferring the longer piece where tied."""
    n = len(word)
    dp = [0] * (n + 1)
    back = [1] * (n + 1)
    for i in range(1, n + 1):
        best, take = dp[i - 1] + 1, 1
        for length in range(MIN_LEN, min(max_len, i) + 1):
            if word[i - length:i] in grams and dp[i - length] + 1 <= best:
                best, take = dp[i - length] + 1, length
        dp[i], back[i] = best, take
    pieces, i = [], n
    while i:
        pieces.append(word[i - back[i]:i])
        i -= back[i]
    return pieces[::-1]


def lesson_words(words, index, grams, max_len):
    """Words that want `grams[index]` and nothing else, most frequent first."""
    gram = grams[index]
    before, after = set(grams[:index]), set(grams[:index + 1])
    all_grams = set(grams)
    out = []
    for word in words:
        if gram not in word:
            continue
        if cost(word, {gram}, max_len) != cost(word, all_grams, max_len):
            continue
        if cost(word, before, max_len) > cost(word, after, max_len):
            out.append(word)
    return out


def review_words(words, learned, all_grams, max_len, limit):
    """A mixed list over `learned`, round-robin so every chord appears."""
    buckets = {g: [] for g in learned}
    known = set(learned)
    for word in words:
        if cost(word, known, max_len) != cost(word, all_grams, max_len):
            continue
        used = [p for p in segment(word, known, max_len) if len(p) > 1]
        for gram in dict.fromkeys(used):
            buckets[gram].append(word)

    out, seen = [], set()
    while len(out) < limit and any(buckets.values()):
        for gram in learned:
            while buckets[gram]:
                word = buckets[gram].pop(0)
                if word not in seen:
                    seen.add(word)
                    out.append(word)
                    break
            if len(out) >= limit:
                break
    return out


def capitals(words, gram, max_len):
    """Words the gram starts, capitalised -- the `+Sp` half of the chord."""
    return [w.capitalize() for w in words
            if segment(w, {gram}, max_len)[0] == gram]


def wrap(words, width=WRAP):
    lines, line = [], ""
    for word in words:
        if line and len(line) + 1 + len(word) > width:
            lines.append(line)
            line = word
        else:
            line = f"{line} {word}" if line else word
    if line:
        lines.append(line)
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-n", "--count", type=int, default=40,
                        help="words per lesson (default 40)")
    parser.add_argument("--review", type=int, default=3, metavar="N",
                        help="a combined list every N lessons (default 3)")
    parser.add_argument("--review-count", type=int, default=100,
                        help="words per review list (default 100)")
    parser.add_argument("--caps", type=int, default=8,
                        help="capitalised words per lesson (default 8)")
    parser.add_argument("--lesson", metavar="GRAM",
                        help="print just this lesson's words, no markdown")
    parser.add_argument("--words", type=Path, default=DEFAULT_WORDS)
    parser.add_argument("--table", type=Path, default=DEFAULT_TABLE)
    args = parser.parse_args()

    grams = read_grams(args.table)
    words = load_words(args.words)
    all_grams = set(grams)
    max_len = max(len(g) for g in grams)

    if args.lesson:
        if args.lesson not in all_grams:
            raise SystemExit(f"{args.lesson} is not in the chord table")
        picked = lesson_words(words, grams.index(args.lesson), grams, max_len)
        print(wrap(picked[:args.count]))
        return

    print(PREAMBLE.format(count=len(grams), review=args.review))

    for i, gram in enumerate(grams, 1):
        picked = lesson_words(words, i - 1, grams, max_len)
        head = picked[:args.count]
        print(f"## Lesson {i} — `{gram}`\n")
        print(f"{len(picked)} words in the list qualify; "
              f"{len(head)} here, most common first.\n")
        print("```")
        print(wrap(head))
        print("```\n")
        caps = capitals(picked, gram, max_len)[:args.caps]
        if caps:
            print(f"Capitals (`{gram.capitalize()}`, the `+Sp` twin):\n")
            print("```")
            print(wrap(caps))
            print("```\n")

        done = i == len(grams)
        if done or (args.review and i % args.review == 0):
            learned = grams[:i]
            mixed = review_words(words, learned, all_grams, max_len,
                                 args.review_count)
            title = "Everything" if done else f"Review 1–{i}"
            print(f"### {title}: {' '.join(f'`{g}`' for g in learned)}\n")
            print(f"{len(mixed)} words, using only these chords.\n")
            print("```")
            print(wrap(mixed))
            print("```\n")


if __name__ == "__main__":
    main()
