#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Build MonkeyType practice lists for the n-gram chords in `TAIPO_ACTIONS`.

The grams and their order come from the chord table itself, so the drills stay
in step with the firmware: the table is written easiest chord first, which is
also the order they are worth learning in.

A lesson is usually one gram, but an entry that extends the one before it in
the table -- `ing` after `in`, `ation` after `tion` -- is taught with it.  Such
a gram takes a large share of what its base would otherwise type, so learning
the base by itself trains a habit the extension has to break.

Nothing outside the keyboard can tell whether a word was typed with its chord
or spelled out letter by letter, so the lists do the enforcing instead.  A word
belongs to a lesson only when the lesson's own grams `L` segment it as cheaply
as the whole table does:

    cost(word, L) == cost(word, all grams)

and the chords learned before it do not already type the word that cheaply:

    cost(word, learned before L) > cost(word, learned including L)

The first rule keeps out words that want a chord you have not learned yet --
`nation` is a `tion` word and never an `on` word, because `n a tion` beats
`n a t i on` -- and words that want an earlier chord as well, so a lesson word
is only ever this lesson's chords.  The second keeps out words where a chord
you already have does the same job: `more` is not an `or` word, because
`m o re` costs what `m or e` does and `re` came first.  Between them, every
optimal way to type a lesson word uses that lesson's chords.

Review lists relax that to the grams learned so far, and round-robin over them
so each chord in the set gets a turn.

Usage:
    uv run words/drills.py > docs/taipo-drills.md   # the readable version
    uv run words/drills.py --files                  # one file per drill
    uv run words/drills.py -n 50 --review 2 --files
"""

import argparse
import json
import re
import sys
import textwrap
import urllib.request
from pathlib import Path

# MonkeyType's own list, so the drills are drawn from the vocabulary the
# practice is done in.  Ignored by git and fetched on first use, as
# `ngrams.py` does with the Norvig corpus.
WORDS_URL = ("https://raw.githubusercontent.com/monkeytypegame/monkeytype/"
             "master/frontend/static/languages/english_10k.json")
DEFAULT_WORDS = Path(__file__).with_name("english_10k.json")
DEFAULT_DIR = Path(__file__).parent.parent / "docs" / "drills"
DEFAULT_TABLE = (Path(__file__).parent.parent
                 / "bbq-keyboard" / "src" / "layout" / "taipo.rs")

MIN_LEN = 2
WRAP = 88


PREAMBLE = """# Taipo n-gram drills

Practice lists for the n-gram chords, generated by `words/drills.py` from the
{count} `Action::Text` entries in `TAIPO_ACTIONS`.  The table is written
easiest chord first, which is also the order they are worth learning in, so
the {lessons} lessons follow it.  Regenerate with:

```
uv run words/drills.py > docs/taipo-drills.md
uv run words/drills.py --files
```

See [ngrams-results.md](ngrams-results.md) for where the grams came from and
which chord each one sits on.

## How to use these

Every drill is also a file in [{dir}/]({dir}/), one line, no newlines --
MonkeyType's custom text treats a newline as a character to type, so the
wrapped blocks below are for reading and the files are what to paste:

```
pbcopy < docs/{first}
```

Then MonkeyType: **custom text**, paste, turn *random* on and set a word count.
Punctuation and numbers off; its own capitalisation option is the way to reach
the `+Sp` half of a chord, so the lists are all lower case.

In {pairs} of the {lessons} lessons two chords arrive together, because
{paired} each take a third to a half of what the gram before them would
otherwise type.  Learning `in` by itself would train `in`+`g` across a third
of its uses, for `ing` to undo later.  The third list in those lessons mixes
the pair, which is the drill that matters: the same `in` is the whole answer
in one word and the front of `ing` in the next.

Nothing outside the keyboard can see whether a word was chorded or spelled out,
so the lists do the enforcing.  A word is in a lesson only if two things hold:
no chord past it would type the word any cheaper, and no chord before it
already does.  So while typing a lesson, **every word in front of you has
exactly one best answer and it is today's chord** -- if you spell one out you
will know, because you had no reason to be there.  `nation` is a `tion` word
and never an `on` word; `more` is not an `or` word, because `re` came first and
`m o re` already costs three.

Speed is the wrong measure at first.  A chord you have to think about is slower
than the letters it replaces, and stays slower for a while; the drill is for
the recognition, not the pace.  Watch instead for whether the gram is being
*seen* -- `otherwise` as `o-the-r-w-i-s-e` rather than nine letters.

A review list appears every {review} lessons and at the end, mixing everything
learned so far.  Those are where the chords stop being an exercise: the words
are ordinary, the grams are wherever they fall, and nothing marks them.

Each lesson's words are the most common qualifying ones from MonkeyType's
`english_10k`; `-n` takes more per lesson if a list goes stale.
"""


def read_grams(path, table="TAIPO_ACTIONS"):
    """The `Action::Text` grams of a chord table, in table order.

    Only the lower-case entries: each gram has a `+Sp` twin typing it
    capitalised, which is the same chord and not a separate thing to learn.
    """
    source = path.read_text(encoding="utf-8")
    match = re.search(rf"static {table}[^=]*=\s*&?\[(.*?)\n\];", source, re.S)
    if not match:
        raise SystemExit(f"no table {table} found in {path}")
    grams = []
    for text in re.findall(r'action:\s*Action::Text\("([^"]+)"\)',
                           match.group(1)):
        if text.islower() and text not in grams:
            grams.append(text)
    return grams


def load_words(path, url=WORDS_URL):
    """The MonkeyType list, most frequent first, proper nouns dropped."""
    if not path.exists():
        print(f"downloading {url} -> {path}", file=sys.stderr)
        urllib.request.urlretrieve(url, path)
    data = json.loads(path.read_text(encoding="utf-8"))
    words = data["words"] if isinstance(data, dict) else data
    seen, out = set(), []
    for word in words:
        if word.isalpha() and word.islower() and word not in seen:
            seen.add(word)
            out.append(word)
    return out


def cost(word, grams, max_len):
    """Fewest chords `word` segments into, given the grams that have chords."""
    n = len(word)
    dp = [0] * (n + 1)
    for i in range(1, n + 1):
        best = dp[i - 1] + 1
        for length in range(MIN_LEN, min(max_len, i) + 1):
            if word[i - length:i] in grams and dp[i - length] + 1 < best:
                best = dp[i - length] + 1
        dp[i] = best
    return dp[n]


def segment(word, grams, max_len):
    """A cheapest segmentation, preferring the longer piece where tied."""
    n = len(word)
    dp = [0] * (n + 1)
    back = [1] * (n + 1)
    for i in range(1, n + 1):
        best, take = dp[i - 1] + 1, 1
        for length in range(MIN_LEN, min(max_len, i) + 1):
            if word[i - length:i] in grams and dp[i - length] + 1 <= best:
                best, take = dp[i - length] + 1, length
        dp[i], back[i] = best, take
    pieces, i = [], n
    while i:
        pieces.append(word[i - back[i]:i])
        i -= back[i]
    return pieces[::-1]


def split_lessons(grams):
    """The table grouped into lessons, an extension joining its base.

    A gram that contains the gram before it extends it, and takes a large
    part of what it would otherwise type, so the two are learned at once.
    Only the pair: a third gram starts a lesson of its own.
    """
    out = []
    for gram in grams:
        if out and len(out[-1]) == 1 and out[-1][0] in gram:
            out[-1].append(gram)
        else:
            out.append([gram])
    return out


def lesson_words(words, index, lessons, max_len):
    """Words that want `lessons[index]` and nothing else, frequent first."""
    lesson = set(lessons[index])
    before = {g for group in lessons[:index] for g in group}
    after = before | lesson
    all_grams = {g for group in lessons for g in group}
    out = []
    for word in words:
        if not any(gram in word for gram in lesson):
            continue
        if cost(word, lesson, max_len) != cost(word, all_grams, max_len):
            continue
        if cost(word, before, max_len) > cost(word, after, max_len):
            out.append(word)
    return out


def by_gram(picked, lesson, max_len):
    """The lesson's words grouped by which of its chords they use."""
    groups = {}
    for word in picked:
        used = {p for p in segment(word, set(lesson), max_len) if len(p) > 1}
        groups.setdefault(tuple(g for g in lesson if g in used),
                          []).append(word)
    return groups


def interleave(pools, limit):
    """Round-robin, so a mixed drill never runs on one chord for long."""
    out, pools = [], [list(p) for p in pools if p]
    while pools and len(out) < limit:
        for pool in pools:
            if pool:
                out.append(pool.pop(0))
                if len(out) >= limit:
                    break
        pools = [p for p in pools if p]
    return out


def review_words(words, learned, all_grams, max_len, limit):
    """A mixed list over `learned`, round-robin so every chord appears."""
    buckets = {g: [] for g in learned}
    known = set(learned)
    for word in words:
        if cost(word, known, max_len) != cost(word, all_grams, max_len):
            continue
        used = [p for p in segment(word, known, max_len) if len(p) > 1]
        for gram in dict.fromkeys(used):
            buckets[gram].append(word)

    out, seen = [], set()
    while len(out) < limit and any(buckets.values()):
        for gram in learned:
            while buckets[gram]:
                word = buckets[gram].pop(0)
                if word not in seen:
                    seen.add(word)
                    out.append(word)
                    break
            if len(out) >= limit:
                break
    return out



def reflow(text, width=79):
    """Refill the prose paragraphs, which interpolation has left ragged."""
    out, fenced = [], False
    for para in text.split("\n\n"):
        if para.startswith("```") or fenced:
            fenced = para.count("```") % 2 == 1 if not fenced else False
            out.append(para)
        elif para.startswith("#"):
            out.append(para)
        else:
            out.append(textwrap.fill(para, width, fix_sentence_endings=True,
                                     break_long_words=False,
                                     break_on_hyphens=False))
    return "\n\n".join(out)


def wrap(words, width=WRAP):
    lines, line = [], ""
    for word in words:
        if line and len(line) + 1 + len(word) > width:
            lines.append(line)
            line = word
        else:
            line = f"{line} {word}" if line else word
    if line:
        lines.append(line)
    return "\n".join(lines)


def build(words, grams, args):
    """Every drill, grouped into the lessons they are worked through in."""
    lessons = split_lessons(grams)
    all_grams = set(grams)
    max_len = max(len(g) for g in grams)
    out = []
    for i, lesson in enumerate(lessons, 1):
        blocks = []
        picked = lesson_words(words, i - 1, lessons, max_len)
        groups = by_gram(picked, lesson, max_len)
        for gram in lesson:
            alone = groups.get((gram,), [])
            blocks.append({"kind": "lesson", "gram": gram, "slug": gram,
                           "words": alone[:args.count], "total": len(alone)})
        if len(lesson) > 1:
            # Words using both first: they are the sharpest form of the
            # question, the same letters answered two ways in one word.
            pools = [groups.get(tuple(lesson), [])]
            pools += [groups.get((gram,), []) for gram in lesson]
            blocks.append({"kind": "mixed", "grams": lesson,
                           "slug": "-".join(lesson),
                           "words": interleave(pools, args.count)})
        final = i == len(lessons)
        if final or (args.review and i % args.review == 0):
            learned = [g for group in lessons[:i] for g in group]
            blocks.append({"kind": "review", "learned": learned,
                           "final": final,
                           "slug": "review-all" if final else "review",
                           "words": review_words(words, learned, all_grams,
                                                 max_len, args.review_count)})
        for letter, block in zip("abcdefgh", blocks):
            block["n"] = i
            block["file"] = f"{i:02d}{letter}-{block['slug']}.txt"
        out.append({"n": i, "grams": lesson, "blocks": blocks})
    return out


def write_files(lessons, directory):
    """One file per drill, a single line each -- MonkeyType eats newlines.

    Files this tool owns are cleared first, so a changed chord table does
    not leave a stale drill behind.
    """
    directory.mkdir(parents=True, exist_ok=True)
    for stale in directory.glob("[0-9][0-9]*.txt"):
        stale.unlink()
    for lesson in lessons:
        for block in lesson["blocks"]:
            path = directory / block["file"]
            # No trailing newline: `pbcopy` would put it on the clipboard.
            path.write_text(" ".join(block["words"]), encoding="utf-8")
            print(f"{path.name:24s} {len(block['words']):4d} words",
                  file=sys.stderr)


def heading(lesson):
    grams = " and ".join(f"`{g}`" for g in lesson["grams"])
    return f"## Lesson {lesson['n']} — {grams}"


def intro(block, lesson):
    """The line above a drill, saying what it is for."""
    if block["kind"] == "lesson":
        what = (f"`{block['gram']}` alone" if len(lesson["grams"]) > 1
                else f"`{block['gram']}`")
        return (f"{what} — {block['total']} words in the list qualify, "
                f"{len(block['words'])} here, most common first.")
    if block["kind"] == "mixed":
        base, ext = lesson["grams"]
        where = ("the front of" if ext.startswith(base) else
                 "the tail of" if ext.endswith(base) else "part of")
        return (f"Both, mixed — the drill that matters, where the same "
                f"`{base}` is the whole answer in one word and {where} "
                f"`{ext}` in the next.")
    learned = " ".join(f"`{g}`" for g in block["learned"])
    title = ("Everything" if block["final"]
             else f"Review through lesson {block['n']}")
    return f"### {title}: {learned}\n\n{len(block['words'])} words."


def markdown(lessons, grams, args, directory):
    """The readable version: the same drills, wrapped, with the commentary."""
    pairs = [l for l in lessons if len(l["grams"]) > 1]
    print(reflow(PREAMBLE.format(
        count=len(grams), review=args.review, lessons=len(lessons),
        pairs=len(pairs), dir=directory.name,
        first=f"{directory.name}/{lessons[0]['blocks'][0]['file']}",
        paired=", ".join(f"`{l['grams'][1]}`" for l in pairs))))
    for lesson in lessons:
        print(f"{heading(lesson)}\n")
        for block in lesson["blocks"]:
            print(f"{reflow(intro(block, lesson))}\n")
            print(f"`{directory.name}/{block['file']}`\n")
            print("```")
            print(wrap(block["words"]))
            print("```\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-n", "--count", type=int, default=40,
                        help="words per drill (default 40)")
    parser.add_argument("--review", type=int, default=3, metavar="N",
                        help="a combined list every N lessons (default 3)")
    parser.add_argument("--review-count", type=int, default=100,
                        help="words per review list (default 100)")
    parser.add_argument("--files", type=Path, metavar="DIR", nargs="?",
                        const=DEFAULT_DIR,
                        help=f"write one file per drill into DIR "
                             f"(default {DEFAULT_DIR.name}/) instead of "
                             f"printing markdown")
    parser.add_argument("--words", type=Path, default=DEFAULT_WORDS)
    parser.add_argument("--table", type=Path, default=DEFAULT_TABLE)
    args = parser.parse_args()

    grams = read_grams(args.table)
    words = load_words(args.words)
    lessons = build(words, grams, args)

    if args.files:
        write_files(lessons, args.files)
    else:
        markdown(lessons, grams, args, DEFAULT_DIR)


if __name__ == "__main__":
    main()
